# use microsoft python 3.11 devcontainer image
FROM mcr.microsoft.com/vscode/devcontainers/python:3.11

# install requirements.txt
# Being a little silly - assmuing server people don't carea bout frontend
WORKDIR /workspace/server

COPY ./server/requirements.txt .
RUN pip install -r requirements.txt

WORKDIR /workspace

COPY . .