name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy-key.pem
          chmod 600 ~/.ssh/deploy-key.pem
          cat >>~/.ssh/config <<END
          Host my-vm
            HostName $SSH_IP
            User $SSH_USER
            IdentityFile ~/.ssh/deploy-key.pem
            StrictHostKeyChecking no
          END
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_IP: ${{ secrets.SSH_IP }}

      - name: 🚀 Deploy site
        run: ssh my-vm 'cd ${{ secrets.PROJECT_ROOT }} && ./redeploy-site.sh'

      # https://stackoverflow.com/a/64649397
      - name: 📅 Dynamically set $DATE
        run: echo "DATE=$(date +'%Y-%m-%dT%H:%M:%S.000Z')" >> $GITHUB_ENV

      - name: 💚 Send Deployment Message on Success
        env:
          TITLE: '🚀 Server Deployment Successful!'
          DESCRIPTION: '**Repo:** ${{ github.repository }}\n\n**Commit Hash:** ${{ github.sha }}'
          URL: 'https://github.com/ajsingh1012/MathTTS/${{ github.sha }}'
        # The backslashes around double quotes are annoying but if I use single quotes, discord will say the JSON is invalid for some reason
        run: |
          curl \
            -H "Content-Type: application/json" \
            -d "{ \"embeds\": [{ \"title\": \"$TITLE\", \"description\": \"$DESCRIPTION\", \"timestamp\": \"$DATE\", \"url\": \"$URL\" }]}" \
            "${{ secrets.DISCORD_WEBHOOK }}"

      - name: 🚨 Send Deployment Message on Failure
        if: ${{ failure() }}
        run: curl -s -X POST "${{ secrets.DISCORD_WEBHOOK }}" -d "content=🚨 Deployment failed for commit ${{ github.sha }}!"